# Generated by Django 4.1.4 on 2023-01-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_coins_alter_account_initial_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='coins',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='prices',
            field=models.JSONField(null=True),
        ),
    ]
