version: "3"

services:
  db:
    image: mysql
    container_name: simtrading_db_mysql
    environment:
      MYSQL_DATABASE: simtrading_django
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: ./backend_django
    image: simtrading_backend_django:1.0.0
    container_name: simtrading_backend_django
    command: >
      sh -c "./wait-for-it.sh db:3306 -- 
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      SECRET_KEY: ${SECRET_KEY}
      GOOGLE_OAUTH2_CLIENT_ID: ${GOOGLE_OAUTH2_CLIENT_ID}
      GOOGLE_OAUTH2_CLIENT_SECRET: ${GOOGLE_OAUTH2_CLIENT_SECRET}
      NEWS_API_KEY: ${NEWS_API_KEY}

    volumes:
      - ./backend_django:/api

  frontend:
    build:
      context: ./frontend/react-frontend
      args:
        - REACT_APP_FRONTEND_URL=${FRONTEND_URL}
        - REACT_APP_BACKEND_URL=${BACKEND_URL}
    image: simtrading_frontend_react:1.0.0
    container_name: simtrading_frontend_react
    command: npm start
    ports:
      - "3000:3000"
    depends_on: 
      - backend
      - db
    volumes:
      - ./frontend/react-frontend:/app
      


# volumes:
#   data:
