# Generated by Django 4.1.4 on 2023-01-02 11:51

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Required. 300 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=300, verbose_name='body')),
                ('coin', models.CharField(max_length=100, verbose_name='coin')),
                ('date_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('date_updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
        ),
    ]
